# WEEKLY STOCK DATA

In [1]:
import requests
import alpha_vantage
import pandas as pd
import csv

In [2]:
API_URL = "https://www.alphavantage.co/query"

In [3]:
stocks=["GOOG"]

In [5]:
weekly_open_price=[]
weekly_close_price=[]
weekly_high_price=[]
weekly_low_price=[]
weekly_volume=[]
stock_name=[]
weekly_date=[]


for stock in stocks:
    data_weekly = {
        "function": "TIME_SERIES_WEEKLY",
        "symbol": stock,
        "outputsize": "full",
        "datatype": "json",
        "apikey":"Q9U4GSEBHNGWOD9R" }

    response_weekly = requests.get(API_URL, data_weekly)
    stock_data_weekly=response_weekly.json()
    values_weekly = stock_data_weekly["Weekly Time Series"]
    
    keys_weekly = (values_weekly.keys())

    for key in keys_weekly:
        stock_name.append(stock)
        weekly_date.append(key)
        weekly_open_price.append(values_weekly[key]['1. open'])
        weekly_close_price.append(values_weekly[key]['4. close'])
        weekly_high_price.append(values_weekly[key]['2. high'])
        weekly_low_price.append(values_weekly[key]['3. low'])
        weekly_volume.append(values_weekly[key]['5. volume'])

In [6]:
weekly_stock_df=pd.DataFrame(stock_name, columns=["Stock"])
weekly_stock_df["Date"]= weekly_date
weekly_stock_df["Open"]=weekly_open_price
weekly_stock_df["Close"]=weekly_close_price
weekly_stock_df["High"]=weekly_high_price
weekly_stock_df["Low"]=weekly_low_price
weekly_stock_df["Volume"]=weekly_volume
weekly_stock_df

    Stock        Date       Open      Close       High        Low    Volume
0    GOOG  2018-09-13  1172.1900  1175.3300  1178.6800  1156.2400   5022834
1    GOOG  2018-09-07  1204.2700  1164.8300  1212.9900  1152.0000   7182225
2    GOOG  2018-08-31  1227.6000  1218.1900  1253.6300  1211.2900   6917439
3    GOOG  2018-08-24  1205.0200  1220.6500  1221.6500  1194.6300   4903185
4    GOOG  2018-08-17  1236.9800  1200.9600  1249.2700  1188.2400   6907160
5    GOOG  2018-08-10  1225.0000  1237.6100  1256.5000  1215.8000   5904136
6    GOOG  2018-08-03  1228.0100  1223.7100  1234.9200  1204.7900   7683085
7    GOOG  2018-07-27  1181.0100  1238.5000  1273.8900  1181.0000  12613633
8    GOOG  2018-07-20  1189.3900  1184.9100  1204.5000  1170.6000   6584688
9    GOOG  2018-07-13  1148.4800  1188.8200  1195.4200  1141.0000   5301330
10   GOOG  2018-07-06  1099.0000  1140.1700  1140.9300  1093.8000   3959109
11   GOOG  2018-06-29  1143.6000  1115.6500  1143.9100  1096.0100   7401986
12   GOOG  2018-06-22  1143.6500  1155.4800  1186.2900  1143.5900   7232331
13   GOOG  2018-06-15  1118.6000  1152.2600  1155.4700  1118.6000   6971063
14   GOOG  2018-06-08  1122.3300  1120.8700  1145.7400  1112.1500   8076664
15   GOOG  2018-06-01  1064.8900  1119.5000  1120.0000  1055.2200   8513499
16   GOOG  2018-05-25  1074.0600  1075.6600  1088.0000  1061.7100   4840075
17   GOOG  2018-05-18  1100.0000  1066.3600  1110.7500  1060.6800   6719272
18   GOOG  2018-05-11  1049.2300  1098.2600  1101.3300  1047.1000   7413294
19   GOOG  2018-05-04  1030.0100  1048.2100  1048.5100  1006.2900   8455908
20   GOOG  2018-04-27  1077.8600  1030.0500  1082.7200  1010.5900  13191952
21   GOOG  2018-04-20  1037.0000  1072.9600  1094.1600  1026.7400   8512969
22   GOOG  2018-04-13  1016.8000  1029.2700  1046.4200  1011.3400   7847494
23   GOOG  2018-04-06  1022.8200  1007.0400  1042.7900   990.3700  10549606
24   GOOG  2018-03-29  1046.0000  1031.7900  1064.8400   980.6400  11683961
25   GOOG  2018-03-23  1120.0100  1021.5700  1121.9900  1021.2200  10457958
26   GOOG  2018-03-16  1163.8500  1135.7300  1177.0500  1131.9600   9029817
27   GOOG  2018-03-09  1075.1400  1160.0400  1160.8000  1069.0000   7342745
28   GOOG  2018-03-02  1127.8000  1078.9200  1144.0400  1048.1200   9879470
29   GOOG  2018-02-23  1090.5700  1126.7900  1133.9700  1088.5200   5339418
..    ...         ...        ...        ...        ...        ...       ...
203  GOOG  2014-10-24   509.4500   539.7800   547.2200   508.1000  12172562
204  GOOG  2014-10-17   544.9900   511.1700   549.5000   508.5300  17737539
205  GOOG  2014-10-10   578.8000   544.4900   581.0000   544.0500  10703962
206  GOOG  2014-10-03   571.7500   575.2800   579.8500   563.3200   6658611
207  GOOG  2014-09-26   593.8200   577.1000   593.9490   574.1800   8228835
208  GOOG  2014-09-19   572.9400   596.0800   596.4800   568.2100   9924700
209  GOOG  2014-09-12   586.6000   575.6200   591.7700   574.4600   6500500
210  GOOG  2014-09-05   571.8500   586.0800   586.5500   571.1900   5868000
211  GOOG  2014-08-29   584.7200   571.6000   585.0000   567.0692   7061800
212  GOOG  2014-08-22   576.1100   582.5600   587.3400   576.0000   4989700
213  GOOG  2014-08-15   569.9900   573.4800   579.3800   560.8800   6684900
214  GOOG  2014-08-08   569.0400   568.7700   575.3500   560.0000   6899700
215  GOOG  2014-08-01   588.0700   566.0700   592.5000   562.8500   7390900
216  GOOG  2014-07-25   591.7500   589.0200   599.6500   585.2326   6943000
217  GOOG  2014-07-18   582.6000   595.0800   596.8000   568.6100  11872400
218  GOOG  2014-07-11   583.7600   579.1800   586.4299   565.0100   7050000
219  GOOG  2014-07-03   578.6600   584.7300   585.4399   574.7500   4519900
220  GOOG  2014-06-27   555.1500   577.2400   582.4500   554.2500   9665700
221  GOOG  2014-06-20   549.2600   556.3600   557.5800   539.3300  11821600
222  GOOG  2014-06-13   557.1500   551.7600   563.6000   545.5600   6580300
223  GOOG  2014-06-06   560.7000   556.3300   560.9000   538.7500   8520600
224  GOOG  2014-05-30   556.0000   559.8900   567.8400   554.3500   6862600
225  GOOG  2014-05-23   519.7000   552.7000   553.6400   517.5830   7785500
226  GOOG  2014-05-16   523.5100   520.6300   536.0700   515.4400   7925600
227  GOOG  2014-05-09   524.8200   518.7300   528.9000   503.3000  10369800
228  GOOG  2014-05-02   517.1800   527.9300   533.9999   502.8000  11348700
229  GOOG  2014-04-25   536.1000   516.1800   537.2300   515.4200  10937900
230  GOOG  2014-04-17   538.2500   536.1000   557.0000   518.4601  18083300
231  GOOG  2014-04-11   540.7400   530.6000   565.3700   526.5300  18793800
232  GOOG  2014-04-04   566.8900   543.1400   604.8300   543.0000  11602500

[233 rows x 7 columns]

In [7]:
weekly_stock_df.count()

Stock     233
Date      233
Open      233
Close     233
High      233
Low       233
Volume    233
dtype: int64

In [8]:
weekly_stock_df.to_excel("Output/alpha_vantage_data_weekly.xlsx", index=False)

# DAILY STOCK DATA

In [10]:
daily_open_price=[]
daily_close_price=[]
daily_high_price=[]
daily_low_price=[]
daily_volume=[]
stock_name=[]
daily_date=[]


for stock in stocks:
    data_daily = {
        "function": "TIME_SERIES_DAILY",
        "symbol": stock,
        "outputsize": "full",
        "datatype": "json",
        "apikey":"Q9U4GSEBHNGWOD9R" }

    response_daily = requests.get(API_URL, data_daily)
    stock_data_daily=response_daily.json()
    

    values_daily = stock_data_daily["Time Series (Daily)"]

    
    keys_daily = (values_daily.keys())
    for key in keys_daily:
        stock_name.append(stock)
        daily_date.append(key)
        daily_open_price.append(values_daily[key]['1. open'])
        daily_close_price.append(values_daily[key]['4. close'])
        daily_high_price.append(values_daily[key]['2. high'])
        daily_low_price.append(values_daily[key]['3. low'])
        daily_volume.append(values_daily[key]['5. volume'])

In [11]:
daily_stock_df=pd.DataFrame(stock_name, columns=["Stock"])
daily_stock_df["Date"]=daily_date
daily_stock_df["Open"]=daily_open_price
daily_stock_df["Close"]=daily_close_price
daily_stock_df["High"]=daily_high_price
daily_stock_df["Low"]=daily_low_price
daily_stock_df["Volume"]=daily_volume
daily_stock_df

     Stock        Date       Open      Close       High        Low   Volume
0     GOOG  2018-09-13  1170.7400  1175.3300  1178.6100  1162.8500  1402001
1     GOOG  2018-09-12  1172.7200  1162.8200  1178.6100  1158.3600  1295472
2     GOOG  2018-09-11  1161.6300  1177.3600  1178.6800  1156.2400  1209565
3     GOOG  2018-09-10  1172.1900  1164.6400  1174.5400  1160.1100  1115796
4     GOOG  2018-09-07  1158.6700  1164.8300  1175.2600  1157.2100  1401404
5     GOOG  2018-09-06  1186.3000  1171.4400  1186.3000  1152.0000  1888467
6     GOOG  2018-09-05  1193.8000  1186.4800  1199.0100  1162.0000  2061309
7     GOOG  2018-09-04  1204.2700  1197.0000  1212.9900  1192.5000  1831045
8     GOOG  2018-08-31  1234.9800  1218.1900  1238.6600  1211.2900  1816426
9     GOOG  2018-08-30  1244.2300  1239.1200  1253.6300  1232.5900  1331439
10    GOOG  2018-08-29  1237.4500  1249.3000  1250.6600  1236.3600  1309312
11    GOOG  2018-08-28  1241.2900  1231.1500  1242.5500  1228.6900  1304007
12    GOOG  2018-08-27  1227.6000  1241.8200  1243.0900  1225.7200  1156255
13    GOOG  2018-08-24  1208.8200  1220.6500  1221.6500  1206.3600   946840
14    GOOG  2018-08-23  1207.1400  1205.3800  1221.2800  1204.2400   992604
15    GOOG  2018-08-22  1200.0000  1207.3300  1211.8400  1199.0000   887389
16    GOOG  2018-08-21  1208.0000  1201.6200  1217.2600  1200.3500  1205580
17    GOOG  2018-08-20  1205.0200  1207.7700  1211.0000  1194.6300   870772
18    GOOG  2018-08-17  1202.0300  1200.9600  1209.0200  1188.2400  1389645
19    GOOG  2018-08-16  1224.7300  1206.4900  1226.0000  1202.5500  1343161
20    GOOG  2018-08-15  1229.2600  1214.3800  1235.2400  1209.5100  1828814
21    GOOG  2018-08-14  1235.1900  1242.1000  1245.8700  1225.1100  1348194
22    GOOG  2018-08-13  1236.9800  1235.0100  1249.2700  1233.6400   997346
23    GOOG  2018-08-10  1243.0000  1237.6100  1245.6900  1232.0000  1108919
24    GOOG  2018-08-09  1249.9000  1249.1000  1255.5400  1246.0100   848601
25    GOOG  2018-08-08  1240.4700  1245.6100  1256.5000  1238.0100  1370913
26    GOOG  2018-08-07  1237.0000  1242.2200  1251.1700  1236.1700  1493980
27    GOOG  2018-08-06  1225.0000  1224.7700  1226.0900  1215.8000  1081723
28    GOOG  2018-08-03  1229.6200  1223.7100  1230.0000  1215.0600  1089896
29    GOOG  2018-08-02  1205.9000  1226.1500  1229.8800  1204.7900  1531299
...    ...         ...        ...        ...        ...        ...      ...
1096  GOOG  2014-05-08   508.4600   511.0000   517.2300   506.4500  2015800
1097  GOOG  2014-05-07   515.7900   509.9600   516.6800   503.3000  3215500
1098  GOOG  2014-05-06   525.2300   515.1400   526.8100   515.0600  1684400
1099  GOOG  2014-05-05   524.8200   527.8100   528.9000   521.3200  1021300
1100  GOOG  2014-05-02   533.7600   527.9300   533.9999   525.6100  1683900
1101  GOOG  2014-05-01   527.1100   531.3500   532.9300   523.8800  1900300
1102  GOOG  2014-04-30   527.6000   526.6600   528.0000   522.5200  1746400
1103  GOOG  2014-04-29   516.9000   527.7000   529.4600   516.3200  2691700
1104  GOOG  2014-04-28   517.1800   517.1500   518.6000   502.8000  3326400
1105  GOOG  2014-04-25   522.5100   516.1800   524.7000   515.4200  2094600
1106  GOOG  2014-04-24   530.0700   525.1600   531.6500   522.1200  1878000
1107  GOOG  2014-04-23   533.7900   526.9400   533.8700   526.2500  2046700
1108  GOOG  2014-04-22   528.6400   534.8100   537.2300   527.5100  2358900
1109  GOOG  2014-04-21   536.1000   528.6200   536.7000   525.6000  2559700
1110  GOOG  2014-04-17   548.8100   536.1000   549.5000   531.1500  6790900
1111  GOOG  2014-04-16   543.0000   556.5400   557.0000   540.0000  4879900
1112  GOOG  2014-04-15   536.8200   536.4400   538.4500   518.4601  3844500
1113  GOOG  2014-04-14   538.2500   532.5200   544.1000   529.5610  2568000
1114  GOOG  2014-04-11   532.5500   530.6000   540.0000   526.5300  3914100
1115  GOOG  2014-04-10   565.0000   540.9500   565.0000   539.9000  4025800
1116  GOOG  2014-04-09   559.6200   564.1400   565.3700   552.9500  3321700
1117  GOOG  2014-04-08   542.6000   554.9000   555.0000   541.6100  3142600
1118  GOOG  2014-04-07   540.7400   538.1500   548.4800   527.1500  4389600
1119  GOOG  2014-04-04   574.6500   543.1400   577.7700   543.0000  6351900
1120  GOOG  2014-04-03   569.8500   569.7400   587.2800   564.1300  5085200
1121  GOOG  2014-04-02   565.1060   567.0000   604.8300   562.1900   146700
1122  GOOG  2014-04-01   558.7100   567.1600   568.4500   558.7100     7900
1123  GOOG  2014-03-31   566.8900   556.9700   567.0000   556.9300    10800
1124  GOOG  2014-03-28   561.2000   559.9900   566.4300   558.6700    41100
1125  GOOG  2014-03-27   568.0000   558.4600   568.0000   552.9200    13100

[1126 rows x 7 columns]

In [12]:
daily_stock_df.to_excel("Output/alpha_vantage_data_daily.xlsx", index=False)